feat: editor katext extension
halo-sigs/plugin-katex pull request #3
Opened 2023-07-06 12:59 UTC by gengxiaoxiaoxin

Katex extension is coming. 🎇
Consistent editing experience with the [richtext-editor](https://github.com/halo-sigs/richtext-editor). 

There are currently some known minor issues.
- The bubble menu should not appear when clicking on a formula.
- The style of the formula component is not attractive enough.

Anyway, it's time to experience the formula plugin!

https://github.com/halo-sigs/plugin-katex/assets/29268441/ae8bec54-0d42-4b45-8a27-60077dd6a991

2023-07-06 13:01 UTC, gengxiaoxiaoxin commented
whether to merge or not requires everyone's vote.

2023-07-07 06:25 UTC, ruibaby reviewed
/lgtm

<img width="1653" alt="image" src="https://github.com/halo-sigs/plugin-katex/assets/21301288/3ce4adee-7c75-4f5c-957b-7c9895e2d7d7">

2023-07-07 06:25 UTC, ruibaby commented
@halo-sigs/halo cc

2023-07-07 06:32 UTC, LIlGG requested changes

2023-07-07 06:32 UTC, LIlGG commented on console/package.json
>      "@halo-dev/console-shared": "^2.6.0",
```suggestion
    "@halo-dev/console-shared": "^2.7.0",
```

2023-07-08 04:01 UTC, merged